version: '2'
services:
  proxy:
    image: nginx
    restart: always
    logging:
      driver: "journald"
    ports:
      - "80:80"
    volumes:
      - /root/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/share:/opt/share
      - /root/nginx/index.html:/usr/share/nginx/html/index.html
 
